version: 0.2

phases:
  pre_build:
    commands:
      - echo Install Apache Server...
  build:
    commands:
      - echo Build started on `date`
      - sudo yum install -y httpd
  post_build:
    commands:
      - echo Build completed on `date` and started Apache server
      - sudo service httpd start
artifacts:
  files:
    - "**/*"
